############# English navigation ##############

# main menu
[[main]]
name = "首頁"
pageRef = "/"
weight = 1

[[main]]
name = "關於"
pageRef = "/about"
weight = 2

[[main]]
name = "Podcast"
pageRef = "/Podcast"
weight = 3

[[main]]
name = "書單"
pageRef = "/reading_list"
weight = 4

[[main]]
name = "文章"
pageRef = "/blog"
weight = 5

[[main]]
weight = 6
name = "更多"



[[main]]
parent = "更多"
name = "Contact"
pageRef = "/contact"

[[main]]
parent = "更多"
name = "Authors"
pageRef = "/authors"

[[main]]
parent = "更多"
name = "Categories"
pageRef = "/categories"


# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Podcast"
pageRef = "/Podcast"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
